## Project information
site_name: 30DCMQGISPE
site_url: https://qgispe.github.io/30DayMapChallengeQGISPERU
site_description: Mapatón orientada a compartir mapas temáticos diversos por cada día del mes, empleando software libre de código abierto..
site_author: qgispe

## Repository
repo_name: 30DaysMapChallengeQGISPE
repo_url: https://github.com/qgispe/30DayMapChallengeQGISPERU/
edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: <a href="https://twitter.com/antony_barja" title="@antony_barja" target="_blank">Creado por <b>Antony Barja| @antony_barja</b></a> | <a href="https://creativecommons.org/licenses/by-sa/4.0/!" title="Se non specificato diversamente, tutti i contenuti sono soggetti alla licenza Creative Commons Attribution-ShareAlike 4.0 licence (CC BY-SA)" target="_blank" class="link-dark text-decoration-none">Licenza CC-BY-SA-4.0</a>

## Social Media
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/solid/home
      link: https://qgispe.github.io/30DayMapChallengeQGISPERU/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/qgispe
      name: Grupo Oficial de Usuarios QGIS Perú
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/qgispe
      name: Grupo de Usuarios QGIS Perú
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gbvitrano/MaterialMkDocs-gb
      name: Repoisitory GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/qgisperu
      name: Grupo de telegram
    - icon: fontawesome/solid/file-pdf
      link: ../Dagli_OpenData_all_OpenSource_ Lavorare_in_QGIG_con_le_mappe_catastali.pdf
      name: Scarica il file PDF (5.4 mb)
  # analytics:
  #   provider: google
  #   property: UA-122084242-1

# Configuration
theme:
  name: material
  #custom_dir: docs/overrides/
  static_templates:
    - 404.html
  language: es
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: green
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Lato
    code: Roboto Mono
  favicon: imgs/favicon.ico
  icon:
    #  logo: fontawesome/solid/book-reader
  logo: imgs/logo_white.svg
plugins:
- search
- mkdocstrings
- autolinks
- macros
# - img2fig
- print-site:
    add_to_navigation: false
    print_page_title: 'Stampa il documento in pdf'
    add_print_site_banner: true
    print_site_banner_template: "docs/pdf/banner.tpl"
    # Table of contents
    add_table_of_contents: true
    toc_title: 'Mapatón orientada a compartir mapas temáticos diversos por cada día del mes, empleando software libre de código abierto'
    toc_depth: 6
    # Content-related
    add_full_urls: true
    enumerate_headings: true
    enumerate_figures: true
    add_cover_page: true
    cover_page_template: "docs/pdf/cover_page.tpl"
    path_to_pdf: "Dagli_OpenData_all_OpenSource_ Lavorare_in_QGIG_con_le_mappe_catastali.pdf"
    exclude:

- rss:
    abstract_chars_count: 160
    date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%d-%m-%Y"
    # datetime_format: "%Y-%m-%d"
    image: https://materialmkdocs-gb.readthedocs.io/it/latest/img/hfc_rss.png
    feed_ttl: 1440
    length: 20
    pretty_print: false
    match_path: ".*"
    url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

markdown_extensions:
- toc:
        permalink: ↵
- meta
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes

## Custom theme additions
extra_javascript:
   - stylesheets/extra.js

extra_css:
   - stylesheets/gbextra.css

## Page tree
nav:
    - Incio: README.md
    - Mapas publicados:
        - Día 01: index.md
        - Día 02: index.md
    - Estadísticas: index.md
    - Cierre del evento: index.md
